project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true